# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Deploy app Digital Ocean

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DO_TOKEN }}
    # - name: Set up SSH
    #   run: |
    #     eval "$(ssh-agent -s)"
    #     ssh-add - < "${{ secrets.SSH_PRIVATE_KEY }}"
    # - name: Deploy to Droplet
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{secrets.IP_PUBLICA}}
    #     cd ./var/www/html/Vue
    #     git pull
    #     npm install
    #     pm2 restart app.js
