name: Deploy App to DigitalOcean

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y doctl

      - name: Store DigitalOcean Token
        run: |
          echo ${{ secrets.DO_TOKEN }} > do_token.txt
          # Consider using a dedicated action for secret handling

      - name: Login to DigitalOcean
        run: |
          chmod 600 do_token.txt  # Set stricter permissions for the token file
          doctl auth init
          doctl auth token set < do_token.txt  # Read the token from the file

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_PUBLICA }}
          username: root  # Consider using a non-root user for security reasons
          script: |
            cd /var/www/html/Vue
            git pull
            npm install
            # Install pm2 if not already installed
            if ! which pm2 >/dev/null; then
              npm install pm2
            fi
            pm2 restart app.js
        # Consider adding error handling for the SSH connection and deployment steps